spring:
  profiles:
    active: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://mysql:3306/vj_airline?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1
        shutdown-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/vj_airline?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=90000&socketTimeout=90000&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&maxReconnects=3&initialTimeout=1
    hikari:
      initialization-fail-timeout: 120000
      connection-timeout: 90000

jwt:
  expiration: 2592000
  secretKey: dc5c9d1c0879a9ea385bd31bec4ee7feb628a5ed6fdc5569426f90fad9294409

session:
  ttl: 3600

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true

cloudinary:
  cloudName: ${CLOUD_NAME}
  apiKey: ${CLOUD_API_KEY}
  apiSecret: ${CLOUD_API_SECRET}

zalo_pay:
  app_id: ${APP_ID}
  mac_key: ${MAC_KEY}
  url_create_order: ${URL_CREATE_ORDER}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  secret: ${PAYPAL_SECRET}
  api-url: ${PAYPAL_API_URL}

auth:
  otp-length: 6
  otp-expiration: 300
  otp-resend-delay: 60

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Thêm logging cho connection debugging
    com.mysql.cj.jdbc: INFO
    org.springframework.retry: DEBUG