spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/vj_airline?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

jwt:
  expiration: 2592000
  secretKey: dc5c9d1c0879a9ea385bd31bec4ee7feb628a5ed6fdc5569426f90fad9294409

session:
  ttl: 3600

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true

cloudinary:
  cloudName: ${CLOUD_NAME}
  apiKey: ${CLOUD_API_KEY}
  apiSecret: ${CLOUD_API_SECRET}

zalo_pay:
  app_id: ${APP_ID}
  mac_key: ${MAC_KEY}
  url_create_order: ${URL_CREATE_ORDER}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  secret: ${PAYPAL_SECRET}
  api-url: ${PAYPAL_API_URL}

auth:
  otp-length: 6
  otp-expiration: 300
  otp-resend-delay: 60

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE